### ISSUE TITLE
Android6.0 received data is not real time

### ISSUE THREAD

**Issue by duhongyu** [NordicSemiconductor/Android-nRF-Toolbox#30] opened 2017-03-23 13:29 UTC
hi, I have a Bluetooth device that send data in 50 Hz  by uart. But I received data is not uniform by 50 Hz
in Android 6.0 huawei P9 and other Android7.0 phone. in Android4.4 is ok.

**Comment by philips77** [comment] 2017-03-23 14:20
Duplicate of #29

**Closed** 2017-06-28 14:56 UTC
